name = "{{project_name}}"
version = "1.0.0"
description = "{{description}}"
gleam = ">= 1.1.0"

[dependencies]
gleam_stdlib = "~> 0.30"
wisp = "~> 1.2.0"
gleam_json = "~> 0.6"
gleam_erlang = "~> 0.23"
mist = ">= 2.0.0 and < 3.0.0"
gleam_http = "~> 3.5"

[dev-dependencies]
gleeunit = "~> 1.0"